options {
    directory "/var/cache/bind";

    listen-on port 53 {
        any;
    };

    listen-on-v6 {
        none;
    };

    allow-query {
        any;
    };

    recursion no;
};

zone "mycompany.com" {
    type primary;
    file "/etc/bind/zones/db.mycompany.com";
    allow-transfer { 172.20.0.11; };
    also-notify { 172.20.0.11; };
};

zone "mycompany.com" {
    type secondary;

    primaries {
        172.20.0.10;
    };

    file "/var/cache/bind/db.mycompany.com";
};