server {
    listen 80;
    server_name localhost;

    root /var/www;

    location / {
        index index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwrded-For $proxy_add_x_forwarded_for;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location ~* \.(jpg|jpeg|gif|bmp|png|webm|ico|css|js|mp3|mp4)$ {
        root /var/www;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}

# Secure SSL certificate configuration
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/nginx.cert;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    # senior security tip; use strong protocols only

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www;

    location / {
        index index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }
}

# Redirect to https from http automatically

server  {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}