upstream nestjs_cluster {
    server nestjs-app:3000; # Use the SERVICE NAME from docker-compose
}

server {
    listen 80;
    server_name localhost;
    root /var/www;

    location / {
        index index.html;
    }

    location /api {
        proxy_pass http://nestjs_cluster; # Nginx uses Docker DNS to find 'nestjs-app'
        proxy_set_header Host $host;
    }

    location ~ \.php$ {
        include fastcgi_params;
        # TCP instead of Unix Socket because PHP is in another container!
        fastcgi_pass php-app:9000; 
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}